SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60

# fsm
STAN_MENU = 0
STAN_OTWIERANIE_JAJKA = 1
STAN_DECYZJA_CZEKOLADA = 2
STAN_DECYZJA_ZABAWKA = 3
STAN_BIEDRONKA = 4
STAN_WYGRANA = 5
STAN_PRZEGRANA_BRZUCH = 6
STAN_PRZEGRANA_ALEX = 7

# inne
NAZWY_FIGUREK = ["Creeper", "Steve", "Zombie", "Swinka", "Enderman", "Szkielet", "Zlota Alex"]
SZANSE_LOSOWANIA = [15, 15, 15, 15, 15, 15, 10]